### ISSUE TITLE
vscode ssh connect error

### ISSUE THREAD

**Issue by cuidong008** [tg123/docker-sshd#5]
![image](https://user-images.githubusercontent.com/13229701/230579398-6bb6a349-2a85-42df-b092-63213107973b.png)

**Comment by tg123** [comment]
seems due to `unhandled req type exec`

**Comment by tg123** [comment]
thank you, this project is created ~8 years ago, yet, I had a very happy weekend debugging it and make vscode supported

https://github.com/tg123/docker-sshd#connecting-from-vscode

![image](https://user-images.githubusercontent.com/170430/230841454-ed275ef1-0da6-4f05-83b9-0905823a0a43.png)
